package com.panda.tokenbucketcruddemo.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for creating/updating a User.
 * Received in POST/PUT request bodies.
 * Does not include id - it's generated by the service.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class UserRequest {
    private String name;
    private String email;
}